name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker-hub.ispider.io", custom_domain = true },
  { pattern = "docker-quay.ispider.io", custom_domain = true },
  { pattern = "docker-gcr.ispider.io", custom_domain = true },
  { pattern = "docker-k8s-gcr.ispider.io", custom_domain = true },
  { pattern = "docker-k8s.ispider.io", custom_domain = true },
  { pattern = "docker-ghcr.ispider.io", custom_domain = true },
  { pattern = "docker-cloudsmith.ispider.io", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
# route = { pattern = "docker-staging.libcuda.so", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
